import 'reflect-metadata';
import { GUARDS_METADATA, METHOD_METADATA, PATH_METADATA } from '@nestjs/common/constants';
import { RequestMethod } from '@nestjs/common';
import { WALLET_ROLES_KEY } from '../wallet-auth/decorators/wallet-roles.decorator';
import { WalletJwtAuthGuard } from '../wallet-auth/guards/wallet-jwt-auth.guard';
import { WalletRolesGuard } from '../wallet-auth/guards/wallet-roles.guard';
import { CustomerFeaturesController } from './customer-features.controller';

type RouteContract={handler:keyof CustomerFeaturesController;method:RequestMethod;path:string;role:'CUSTOMER'|'ADMIN';owner:string;unauthorized:401;forbidden:403|null;notFound:404|null;idempotency:string};
const customer=(handler:RouteContract['handler'],method:RequestMethod,path:string,owner:string,idempotency='none'):RouteContract=>({handler,method,path,role:'CUSTOMER',owner,unauthorized:401,forbidden:403,notFound:404,idempotency});
const admin=(handler:RouteContract['handler'],method:RequestMethod,path:string):RouteContract=>({handler,method,path,role:'ADMIN',owner:'ADMIN role; target is explicit and audited',unauthorized:401,forbidden:403,notFound:404,idempotency:'none'});

export const CUSTOMER_FEATURE_ROUTE_INVENTORY:RouteContract[]=[
  customer('contacts',RequestMethod.GET,'contacts','JWT owner list'),customer('createContact',RequestMethod.POST,'contacts','JWT owner creates'),customer('updateContact',RequestMethod.PATCH,'contacts/:id','contact.ownerUserId'),customer('deleteContact',RequestMethod.DELETE,'contacts/:id','contact.ownerUserId'),customer('favourite',RequestMethod.POST,'contacts/:id/favourite','contact.ownerUserId'),customer('unfavourite',RequestMethod.DELETE,'contacts/:id/favourite','contact.ownerUserId'),
  customer('moneyRequests',RequestMethod.GET,'money-requests','JWT requester or payer'),customer('createMoneyRequest',RequestMethod.POST,'money-requests','JWT requester; payer is target','idempotencyKey'),customer('acceptMoneyRequest',RequestMethod.POST,'money-requests/:id/accept','payer only','transfer idempotencyKey'),customer('declineMoneyRequest',RequestMethod.POST,'money-requests/:id/decline','payer only'),customer('cancelMoneyRequest',RequestMethod.POST,'money-requests/:id/cancel','requester only'),
  customer('splits',RequestMethod.GET,'splits','JWT creator or participant'),customer('createSplit',RequestMethod.POST,'splits','JWT creator; participants validated','idempotencyKey'),customer('paySplit',RequestMethod.POST,'split-allocations/:id/pay','allocation participant only','transfer idempotencyKey'),customer('cancelSplit',RequestMethod.POST,'splits/:id/cancel','split creator only'),
  customer('offers',RequestMethod.GET,'offers','authenticated eligibility'),customer('offer',RequestMethod.GET,'offers/:id','authenticated eligibility'),customer('claimOffer',RequestMethod.POST,'offers/:id/claim','claim user is JWT identity','unique offerId/userId'),
  customer('providerStatus',RequestMethod.GET,'providers/status','authenticated'),customer('insights',RequestMethod.GET,'insights','JWT-owned wallets and activity'),customer('recharges',RequestMethod.GET,'recharges','JWT owner list'),customer('rechargePlans',RequestMethod.GET,'recharges/plans','authenticated'),customer('recharge',RequestMethod.POST,'recharges','JWT owner','idempotencyKey'),
  customer('billPayments',RequestMethod.GET,'bill-payments','JWT owner list'),customer('billers',RequestMethod.GET,'billers','authenticated'),customer('validateBill',RequestMethod.POST,'bills/validate','authenticated'),customer('billPayment',RequestMethod.POST,'bill-payments','JWT owner','idempotencyKey'),
  customer('savedBillers',RequestMethod.GET,'saved-billers','JWT owner list'),customer('createSavedBiller',RequestMethod.POST,'saved-billers','JWT owner creates saved reference','unique user/biller/reference/category'),customer('deleteSavedBiller',RequestMethod.DELETE,'saved-billers/:id','savedBiller.userId'),  customer('billReminders',RequestMethod.GET,'bill-reminders','JWT owner list'),customer('createBillReminder',RequestMethod.POST,'bill-reminders','JWT owner; referenced saved biller must be owned'),customer('deleteBillReminder',RequestMethod.DELETE,'bill-reminders/:id','billReminder.userId'),  customer('mandates',RequestMethod.GET,'mandates','JWT owner list'),customer('mandateDetails',RequestMethod.GET,'mandates/:id','mandate.userId'),customer('mandate',RequestMethod.POST,'mandates','JWT owner','idempotencyKey'),customer('authorizeMandate',RequestMethod.POST,'mandates/:id/authorize','mandate.userId'),customer('pauseMandate',RequestMethod.POST,'mandates/:id/pause','mandate.userId'),customer('resumeMandate',RequestMethod.POST,'mandates/:id/resume','mandate.userId'),customer('cancelMandate',RequestMethod.POST,'mandates/:id/cancel','mandate.userId'),
  customer('cases',RequestMethod.GET,'support-cases','JWT case owner list'),customer('createCase',RequestMethod.POST,'support-cases','JWT owner; linked transaction ownership'),customer('caseDetails',RequestMethod.GET,'support-cases/:id','supportCase.userId'),
  admin('adminOffers',RequestMethod.GET,'admin/offers'),admin('createOffer',RequestMethod.POST,'admin/offers'),admin('updateOffer',RequestMethod.PATCH,'admin/offers/:id'),admin('adminCases',RequestMethod.GET,'admin/support-cases'),admin('updateCase',RequestMethod.PATCH,'admin/support-cases/:id'),admin('adminMoneyRequests',RequestMethod.GET,'admin/money-requests'),admin('adminSplits',RequestMethod.GET,'admin/splits'),admin('adminMandates',RequestMethod.GET,'admin/mandates'),admin('adminProviderStatus',RequestMethod.GET,'admin/providers/status'),
];

describe('Customer feature endpoint authorization inventory',()=>{
  it('contains every declared controller handler exactly once',()=>{const declared=Object.getOwnPropertyNames(CustomerFeaturesController.prototype).filter(name=>name!=='constructor'&&Reflect.getMetadata(PATH_METADATA,CustomerFeaturesController.prototype[name]));expect(new Set(CUSTOMER_FEATURE_ROUTE_INVENTORY.map(x=>x.handler)).size).toBe(CUSTOMER_FEATURE_ROUTE_INVENTORY.length);expect(CUSTOMER_FEATURE_ROUTE_INVENTORY.map(x=>x.handler).sort()).toEqual(declared.sort());expect(CUSTOMER_FEATURE_ROUTE_INVENTORY).toHaveLength(52);});
  it.each(CUSTOMER_FEATURE_ROUTE_INVENTORY)('$method $path has its complete auth contract',route=>{const handler=CustomerFeaturesController.prototype[route.handler];expect(Reflect.getMetadata(PATH_METADATA,handler)).toBe(route.path);expect(Reflect.getMetadata(METHOD_METADATA,handler)).toBe(route.method);expect(route.unauthorized).toBe(401);expect(route.owner).toBeTruthy();expect(route.idempotency).toBeTruthy();if(route.role==='ADMIN'){expect(Reflect.getMetadata(WALLET_ROLES_KEY,handler)).toEqual(['ADMIN']);expect(Reflect.getMetadata(GUARDS_METADATA,handler)).toContain(WalletRolesGuard);expect(route.forbidden).toBe(403);}else expect(Reflect.getMetadata(WALLET_ROLES_KEY,handler)).toBeUndefined();});
  it('protects every route with the class-level JWT guard, including malformed, expired, revoked, and missing tokens',()=>{expect(Reflect.getMetadata(GUARDS_METADATA,CustomerFeaturesController)).toContain(WalletJwtAuthGuard);for(const route of CUSTOMER_FEATURE_ROUTE_INVENTORY)expect(route.unauthorized).toBe(401);});
});
