import 'reflect-metadata';
import { ForbiddenException, INestApplication, NotFoundException, RequestMethod } from '@nestjs/common';
import { METHOD_METADATA, PATH_METADATA } from '@nestjs/common/constants';
import { JwtService } from '@nestjs/jwt'; import { Test } from '@nestjs/testing';
import { WALLET_ROLES_KEY } from '../wallet-auth/decorators/wallet-roles.decorator'; import { WalletAuthModule } from '../wallet-auth/wallet-auth.module';
import { CustomerFeaturesController } from './customer-features.controller'; import { CustomerFeaturesService } from './customer-features.service';

type LiveRoute={handler:string;method:string;path:string;admin:boolean;object:boolean}; const verbs:Record<number,string>={[RequestMethod.GET]:'GET',[RequestMethod.POST]:'POST',[RequestMethod.PATCH]:'PATCH',[RequestMethod.DELETE]:'DELETE'};
const sensitive=['other@example.test','+919999999999','OtherFirst','OtherLast','999999.99','other-wallet','other-transaction','other-mandate','other-provider-reference','private-case-description','private-offer-claim','private-request','private-split'];
describe('Customer features live HTTP authorization and leakage matrix',()=>{jest.setTimeout(60_000);let app:INestApplication|undefined;let base='';let jwt:JwtService;let calls:Record<string,jest.Mock>;const secret='live-http-test-secret-not-a-production-credential';let routes:LiveRoute[];
  beforeAll(async()=>{process.env.JWT_SECRET=secret;calls={};const service=new Proxy({}, {get:(_target,key:string)=>key==='then'?undefined:calls[key]??(calls[key]=jest.fn((...args:unknown[])=>{if(args.includes('other-resource'))throw new ForbiddenException('Resource access denied');if(args.includes('missing-resource'))throw new NotFoundException('Resource not found');return {ok:true};}))});const module=await Test.createTestingModule({imports:[WalletAuthModule],controllers:[CustomerFeaturesController],providers:[{provide:CustomerFeaturesService,useValue:service}]}).compile();app=module.createNestApplication();app.setGlobalPrefix('api/v1');await app.listen(0,'127.0.0.1');const address=app.getHttpServer().address() as {port:number};base=`http://127.0.0.1:${address.port}/api/v1/customer-features`;jwt=new JwtService({secret});routes=Object.getOwnPropertyNames(CustomerFeaturesController.prototype).filter(name=>name!=='constructor').flatMap(handler=>{const fn=CustomerFeaturesController.prototype[handler as keyof CustomerFeaturesController];const path=Reflect.getMetadata(PATH_METADATA,fn) as string|undefined;const method=Reflect.getMetadata(METHOD_METADATA,fn) as number|undefined;if(path===undefined||method===undefined)return[];return[{handler,method:verbs[method],path,admin:Boolean(Reflect.getMetadata(WALLET_ROLES_KEY,fn)),object:path.includes(':id')}];});});afterAll(async()=>{await app?.close();delete process.env.JWT_SECRET;});
  const token=(sub:string,role='USER',expiresIn:string|number='5m')=>jwt.sign({sub,email:`${sub}@example.test`,role},{expiresIn} as never);const send=(route:LiveRoute,authorization?:string,id='own-resource',body:Record<string,unknown>={})=>fetch(`${base}/${route.path.replace(':id',id)}`,{method:route.method,headers:{'content-type':'application/json',...(authorization?{authorization}: {})},...(route.method==='GET'||route.method==='DELETE'?{}:{body:JSON.stringify(body)})});
  it('discovers all 52 Wallet routes from the actual controller',()=>expect(routes).toHaveLength(52));
  it.each(Array.from({length:52},(_,index)=>index))('route %s returns live 401 for absent, malformed, and expired JWTs',async index=>{const route=routes[index];for(const authorization of [undefined,'Bearer malformed',`Bearer ${token('expired','USER','-1s')}`]){const response=await send(route,authorization);expect(response.status).toBe(401);const body=await response.json();expect(body).toEqual(expect.objectContaining({statusCode:401,message:expect.anything()}));for(const value of sensitive)expect(JSON.stringify(body)).not.toContain(value);}});
  it.each(Array.from({length:52},(_,index)=>index))('route %s enforces live Customer/Admin success or 403',async index=>{const route=routes[index];if(route.admin){const denied=await send(route,`Bearer ${token('customer')}`);expect(denied.status).toBe(403);for(const value of sensitive)expect(await denied.clone().text()).not.toContain(value);expect((await send(route,`Bearer ${token('admin','ADMIN')}`)).status).toBeLessThan(300);}else expect((await send(route,`Bearer ${token('customer')}`)).status).toBeLessThan(300);});
  it.each(Array.from({length:52},(_,index)=>index))('object route %s returns live 403/404 without leaking private response data',async index=>{const route=routes[index];if(!route.object||route.admin)return;for(const [id,status] of [['other-resource',403],['missing-resource',404]] as const){const response=await send(route,`Bearer ${token('customer')}`,id);expect(response.status).toBe(status);const body=await response.json();expect(Object.keys(body).sort()).toEqual(expect.arrayContaining(['message','statusCode']));for(const value of sensitive)expect(JSON.stringify(body)).not.toContain(value);}});
  it('keeps JWT identity authoritative during body and query userId override attacks',async()=>{const route=routes.find(item=>item.handler==='createContact');expect(route).toBeDefined();if(!route)return;await send(route,`Bearer ${token('jwt-owner')}`,'own-resource',{userId:'other-user',recipientUserId:'00000000-0000-4000-8000-000000000001'});const contactCall=calls.createContact;expect(contactCall).toBeDefined();expect(contactCall.mock.calls.at(-1)[0]).toBe('jwt-owner');const list=routes.find(item=>item.handler==='contacts');expect(list).toBeDefined();if(!list)return;await fetch(`${base}/${list.path}?userId=other-user`,{headers:{authorization:`Bearer ${token('jwt-owner')}`}});expect(calls.listContacts.mock.calls.at(-1)[0]).toBe('jwt-owner');});
});
