services:
  postgres:
    image: postgres:16
    container_name: payflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow_password
      POSTGRES_DB: payflow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: payflow_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: payflow
      RABBITMQ_DEFAULT_PASS: payflow_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: payflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  rabbitmq_data: