'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { AdminShell, ErrorState, PageHeader } from '../../components/admin';
import { Button, Card, RefreshIcon, Skeleton, StatusBadge } from '../../components/ui';
import { formatTransactionAmount, formatTransactionDate, normalizeTransactionDetail, userName, type TransactionDetail, type TransactionWallet } from '../../components/transactions';
import { AdminApiError, type AdminUser, adminAuthenticatedRequest, clearAdminSession, logoutAdmin, restoreAdminSession } from '../../lib/api';

function message(error: unknown) { if (error instanceof AdminApiError) return `${error.status ? `HTTP ${error.status}: ` : ''}${error.message}`; return error instanceof Error ? error.message : 'Unable to load transaction details'; }
function WalletCard({ title, wallet }: { title: string; wallet: TransactionWallet }) {
  return <Card className="p-5"><h2 className="text-base font-semibold text-slate-900">{title}</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Participant</dt><dd className="mt-1 font-medium text-slate-900">{userName(wallet.user)}</dd><dd className="text-xs text-slate-500">{wallet.user.email}</dd></div><div><dt className="text-xs text-slate-500">Phone</dt><dd className="mt-1 text-slate-800">{wallet.user.phone ?? 'Unavailable'}</dd></div><div><dt className="text-xs text-slate-500">Wallet ID</dt><dd className="mt-1 break-all text-xs text-slate-700">{wallet.id}</dd></div><div><dt className="text-xs text-slate-500">Current wallet balance</dt><dd className="mt-1 font-semibold text-slate-950 tabular-nums">{formatTransactionAmount(wallet.balance, wallet.currency)}</dd><dd className="text-xs text-slate-500">Current value, not balance at transaction time</dd></div><div><dt className="text-xs text-slate-500">Wallet status</dt><dd className="mt-1"><StatusBadge status={wallet.status} /></dd></div><div><dt className="text-xs text-slate-500">Ledger account</dt><dd className="mt-1 text-slate-800">{wallet.ledgerAccount ? `${wallet.ledgerAccount.name} · ${wallet.ledgerAccount.code}` : 'Unavailable'}</dd></div></dl></Card>;
}
function DetailContent({ details }: { details: TransactionDetail }) {
  const item = details.transaction; const context = item.reference ?? item.description ?? 'No reference or description';
  return <>
    <Card className="mt-6 p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-0.5 text-xs font-medium text-slate-700">{details.type}</span><StatusBadge status={item.status} /></div><p className="mt-4 break-all text-sm text-slate-600">{item.id}</p><p className="mt-2 text-sm text-slate-500">{context}</p></div><div className="md:text-right"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Transaction amount</p><p className="mt-2 text-2xl font-semibold text-slate-950 tabular-nums">{formatTransactionAmount(item.amount, item.currency)}</p></div></div><dl className="mt-6 grid gap-4 border-t border-slate-200 pt-5 text-sm sm:grid-cols-2 xl:grid-cols-4"><div><dt className="text-xs text-slate-500">Created</dt><dd className="mt-1 text-slate-800">{formatTransactionDate(item.createdAt)}</dd></div><div><dt className="text-xs text-slate-500">Updated</dt><dd className="mt-1 text-slate-800">{formatTransactionDate(item.updatedAt)}</dd></div><div><dt className="text-xs text-slate-500">Completed</dt><dd className="mt-1 text-slate-800">{formatTransactionDate(item.completedAt)}</dd></div><div><dt className="text-xs text-slate-500">Failure reason</dt><dd className="mt-1 text-slate-800">{item.failureReason ?? 'None reported'}</dd></div></dl></Card>
    <section aria-label="Transaction participants" className="mt-5 grid gap-4 lg:grid-cols-2">{item.wallet ? <WalletCard title={details.type === 'DEPOSIT' ? 'Deposit wallet and user' : 'Withdrawal wallet and user'} wallet={item.wallet} /> : null}{item.sourceWallet ? <WalletCard title="Sender and source wallet" wallet={item.sourceWallet} /> : null}{item.destinationWallet ? <WalletCard title="Receiver and destination wallet" wallet={item.destinationWallet} /> : null}</section>
    <section aria-labelledby="ledger-title" className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-4 sm:px-6"><h2 id="ledger-title" className="text-base font-semibold text-slate-900">Ledger entries</h2><p className="mt-1 text-sm text-slate-500">Ordered double-entry accounting records for this transaction.</p></div>{item.ledgerEntries.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-[13px]"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th scope="col" className="px-5 py-3">Entry</th><th scope="col" className="px-4 py-3">Account</th><th scope="col" className="px-4 py-3 text-right">Amount</th><th scope="col" className="px-5 py-3">Created</th></tr></thead><tbody className="divide-y divide-slate-100">{item.ledgerEntries.map((entry) => <tr key={entry.id}><td className="px-5 py-3"><StatusBadge status={entry.entryType} /></td><td className="px-4 py-3"><p className="font-medium text-slate-900">{entry.ledgerAccount.name}</p><p className="text-xs text-slate-500">{entry.ledgerAccount.code}</p></td><td className="px-4 py-3 text-right font-semibold tabular-nums">{formatTransactionAmount(entry.amount, entry.currency)}</td><td className="px-5 py-3 text-slate-500">{formatTransactionDate(entry.createdAt)}</td></tr>)}</tbody></table></div> : <div className="px-5 py-12 text-center"><p className="font-medium text-slate-800">No ledger entries found</p><p className="mt-1 text-sm text-slate-500">No accounting entries are attached to this transaction.</p></div>}</section>
  </>;
}

export default function TransactionDetailsPage() {
  const router = useRouter(); const params = useParams<{ transactionId: string }>();
  const [admin, setAdmin] = useState<AdminUser | null>(null); const [details, setDetails] = useState<TransactionDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState(''); const [notFound, setNotFound] = useState(false); const controllerRef = useRef<AbortController | null>(null);
  useEffect(() => { void restoreAdminSession().then(setAdmin).catch(() => { clearAdminSession(); router.replace('/login'); }); }, [router]);
  const load = useCallback(async () => {
    if (!admin || !params.transactionId) return; controllerRef.current?.abort(); const controller = new AbortController(); controllerRef.current = controller; setIsLoading(true); setError(''); setNotFound(false);
    try { const response = await adminAuthenticatedRequest<unknown>(`/admin/transactions/${params.transactionId}`, { signal: controller.signal }); if (controller.signal.aborted) return; const normalized = normalizeTransactionDetail(response); if (!normalized) { setNotFound(true); setDetails(null); return; } setDetails(normalized); }
    catch (requestError) { if (controller.signal.aborted) return; if (requestError instanceof AdminApiError && requestError.status === 404) setNotFound(true); else setError(message(requestError)); }
    finally { if (!controller.signal.aborted) setIsLoading(false); }
  }, [admin, params.transactionId]);
  useEffect(() => { void load(); return () => controllerRef.current?.abort(); }, [load]);
  async function handleLogout() { await logoutAdmin(); router.push('/login'); router.refresh(); }
  if (!admin) return <main aria-busy="true" className="min-h-screen bg-[#F6F8FA] p-6"><Skeleton className="mx-auto h-96 max-w-7xl" /></main>;
  return <AdminShell admin={admin} onLogout={() => void handleLogout()}><PageHeader eyebrow="Transaction details" title="Transaction record" description="Read-only details for a supported deposit, withdrawal or transfer." actions={<><Button variant="secondary" onClick={() => router.push('/transactions')}>Back to transactions</Button><Button disabled={isLoading} onClick={() => void load()}><RefreshIcon className={`size-4 ${isLoading ? 'animate-spin' : ''}`} />{isLoading ? 'Loading…' : 'Refresh'}</Button></>} />{isLoading && !details ? <section aria-busy="true" aria-live="polite" className="mt-6 space-y-4"><Skeleton className="h-48" /><Skeleton className="h-56" /><span className="sr-only">Loading transaction details</span></section> : null}{error ? <div className="mt-6"><ErrorState message={error} onRetry={() => void load()} /></div> : null}{notFound ? <div className="mt-6"><ErrorState message="Transaction not found or the response type is unsupported." onRetry={() => void load()} /></div> : null}{details ? <DetailContent details={details} /> : null}<p className="sr-only" aria-live="polite">{isLoading ? 'Loading transaction details' : error || (notFound ? 'Transaction not found' : details ? 'Transaction details loaded' : '')}</p></AdminShell>;
}
