import type { FormEvent } from 'react';
import { Button, Field, Input, Label, Select } from '../ui';
import { TRANSACTION_PAGE_SIZES } from './helpers';

export function TransactionsFilterBar(props: {
  searchInput: string; type: string; status: string; limit: number; activeCount: number; disabled: boolean;
  onSearchInput: (value: string) => void; onType: (value: string) => void; onStatus: (value: string) => void;
  onLimit: (value: number) => void; onSearch: () => void; onClear: () => void;
}) {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); props.onSearch(); }
  return <section aria-labelledby="transaction-filters-title" className="mt-6 rounded-lg border border-slate-200 bg-white p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 id="transaction-filters-title" className="text-sm font-semibold text-slate-900">Filters</h2><span className="text-xs text-slate-500">{props.activeCount} active</span></div><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-[minmax(16rem,1fr)_11rem_11rem_8rem_auto_auto] xl:items-end"><Field><Label htmlFor="transaction-search">Search</Label><Input id="transaction-search" value={props.searchInput} onChange={(event) => props.onSearchInput(event.target.value)} placeholder="Transaction, wallet or reference" /></Field><Field><Label htmlFor="transaction-type">Type</Label><Select id="transaction-type" value={props.type} onChange={(event) => props.onType(event.target.value)}><option value="ALL">All types</option><option value="DEPOSIT">Deposits</option><option value="WITHDRAWAL">Withdrawals</option><option value="TRANSFER">Transfers</option></Select></Field><Field><Label htmlFor="transaction-status">Status</Label><Select id="transaction-status" value={props.status} onChange={(event) => props.onStatus(event.target.value)}><option value="ALL">All statuses</option><option value="PENDING">Pending</option><option value="PROCESSING">Processing</option><option value="COMPLETED">Completed</option><option value="FAILED">Failed</option><option value="REVERSED">Reversed</option></Select></Field><Field><Label htmlFor="transaction-limit">Rows</Label><Select id="transaction-limit" value={props.limit} onChange={(event) => props.onLimit(Number(event.target.value))}>{TRANSACTION_PAGE_SIZES.map((size) => <option key={size} value={size}>{size}</option>)}</Select></Field><Button type="submit" disabled={props.disabled}>Search</Button><Button variant="secondary" disabled={props.disabled || props.activeCount === 0} onClick={props.onClear}>Clear</Button></form></section>;
}
