'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Button, Card, EmptyState, ErrorState, Field, LoadingState, PageContainer, PageHeader } from '../components/customer';
import { userAuthenticatedRequest } from '../lib/api';
type Contact = { id: string; nickname?: string | null; favourite: boolean; recipient: { id: string; firstName: string; lastName?: string | null; vpa?: string | null } };
type Recipient = { userId: string; displayName?: string; vpa?: string };
export default function ContactsPage() {
  const [items, setItems] = useState<Contact[] | null>(null); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setError(''); try { setItems(await userAuthenticatedRequest(`/customer-features/contacts${search.trim() ? `?search=${encodeURIComponent(search.trim())}` : ''}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load contacts'); } }, [search]);
  useEffect(() => { void load(); }, [load]);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setSaving(true); setError(''); setMessage(''); try { const identifier = String(data.get('identifier') ?? '').trim(); const query = new URLSearchParams(identifier.includes('@') ? { vpa: identifier } : { email: identifier }); const result = await userAuthenticatedRequest<{ recipient: Recipient } | Recipient>(`/wallets/wallet-recipients/resolve?${query}`); const recipient = 'recipient' in result ? result.recipient : result; await userAuthenticatedRequest('/customer-features/contacts', { method: 'POST', body: JSON.stringify({ recipientUserId: recipient.userId, nickname: String(data.get('nickname') ?? '').trim() || undefined }) }); setMessage(`${recipient.displayName ?? 'Recipient'} added.`); form.reset(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to add contact'); } finally { setSaving(false); } }
  async function mutate(path: string, options: RequestInit) { setError(''); setMessage(''); try { await userAuthenticatedRequest(`/customer-features${path}`, options); setMessage('Contact updated.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update contact'); } }
  return <main><PageContainer><PageHeader eyebrow="People" title="Contacts and favourites" description="Recipients are verified before being added. Your contact list is private to your authenticated account." />
    <div aria-live="polite" className="mt-5">{message ? <p className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}</p> : null}{error ? <ErrorState message={error} onRetry={() => void load()} /> : null}</div>
    <div className="mt-7 grid gap-6 lg:grid-cols-[22rem_1fr]"><Card className="p-6"><h2 className="text-lg font-bold">Add contact</h2><form className="mt-5 space-y-4" onSubmit={(event) => void add(event)}><Field id="contact-identifier" name="identifier" label="Email or Payflow VPA" required autoComplete="off" /><Field id="contact-nickname" name="nickname" label="Nickname (optional)" maxLength={80} /><Button type="submit" disabled={saving}>{saving ? 'Verifying…' : 'Verify and add'}</Button></form></Card>
      <section aria-labelledby="contacts-list"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><h2 id="contacts-list" className="text-lg font-bold">Saved contacts</h2><form onSubmit={(event) => { event.preventDefault(); void load(); }} className="flex gap-2"><Field id="contact-search" aria-label="Search contacts" label="Search" value={search} onChange={(event) => setSearch(event.target.value)} /><Button type="submit" variant="secondary">Search</Button></form></div><div className="mt-4 space-y-3">{items === null ? <LoadingState /> : items.length === 0 ? <EmptyState title="No contacts found" description="Add a verified Payflow recipient to get started." /> : items.map((item) => <ContactCard key={item.id} item={item} mutate={mutate} />)}</div></section></div>
  </PageContainer></main>;
}
function ContactCard({ item, mutate }: { item: Contact; mutate: (path: string, options: RequestInit) => Promise<void> }) {
  const [nickname, setNickname] = useState(item.nickname ?? ''); const name = item.nickname || [item.recipient.firstName, item.recipient.lastName].filter(Boolean).join(' ');
  return <Card className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-bold">{name}</h3><p className="text-sm text-slate-600">{item.recipient.vpa ?? 'Verified Payflow recipient'}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => void mutate(`/contacts/${item.id}/favourite`, { method: item.favourite ? 'DELETE' : 'POST' })}>{item.favourite ? 'Unfavourite' : 'Favourite'}</Button><Button variant="danger" onClick={() => void mutate(`/contacts/${item.id}`, { method: 'DELETE' })}>Delete</Button></div></div><form className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-end" onSubmit={(event) => { event.preventDefault(); void mutate(`/contacts/${item.id}`, { method: 'PATCH', body: JSON.stringify({ nickname }) }); }}><Field id={`nickname-${item.id}`} label="Nickname" value={nickname} maxLength={80} onChange={(event) => setNickname(event.target.value)} /><Button type="submit" variant="secondary">Save nickname</Button></form></Card>;
}
