'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Button, Card, EmptyState, ErrorState, Field, LoadingState, PageContainer, PageHeader, SelectField, StatusBadge } from '../components/customer';
import { getStoredUser, userAuthenticatedRequest } from '../lib/api';
type Wallet = { id: string; currency: string; status: string };
type Contact = { id: string; nickname?: string | null; recipient: { id: string; firstName: string; lastName?: string | null } };
type Request = { id: string; requesterUserId: string; payerUserId: string; walletId: string; currency: string; amount: string; note?: string | null; status: string; expiresAt: string; requester?: Contact['recipient']; payer?: Contact['recipient'] };
const key = (prefix: string) => `${prefix}:${crypto.randomUUID()}`;
export default function RequestMoneyPage() {
  const [user] = useState(getStoredUser); const [items, setItems] = useState<Request[] | null>(null); const [contacts, setContacts] = useState<Contact[]>([]); const [wallets, setWallets] = useState<Wallet[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (!user) return; setError(''); try { const [requests, people, walletValue] = await Promise.all([userAuthenticatedRequest<Request[]>('/customer-features/money-requests'), userAuthenticatedRequest<Contact[]>('/customer-features/contacts'), userAuthenticatedRequest<Wallet[] | { wallets?: Wallet[] }>(`/wallets/user/${user.id}`)]); setItems(requests); setContacts(people); setWallets(Array.isArray(walletValue) ? walletValue : walletValue.wallets ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load requests'); } }, [user]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setSaving(true); setError(''); try { const wallet = wallets.find((item) => item.id === data.get('walletId')); if (!wallet) throw new Error('Choose a wallet'); await userAuthenticatedRequest('/customer-features/money-requests', { method: 'POST', body: JSON.stringify({ payerUserId: data.get('payerUserId'), walletId: wallet.id, currency: wallet.currency, amount: data.get('amount'), note: data.get('note') || undefined, expiresAt: new Date(String(data.get('expiresAt'))).toISOString(), idempotencyKey: key('request') }) }); setMessage('Money request sent.'); form.reset(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create request'); } finally { setSaving(false); } }
  async function action(item: Request, name: 'accept' | 'decline' | 'cancel', sourceWalletId?: string) { setError(''); try { await userAuthenticatedRequest(`/customer-features/money-requests/${item.id}/${name}`, { method: 'POST', body: JSON.stringify(name === 'accept' ? { sourceWalletId, idempotencyKey: key('accept') } : {}) }); setMessage(`Request ${name}ed.`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : `Unable to ${name} request`); } }
  const incoming = items?.filter((item) => item.payerUserId === user?.id) ?? []; const outgoing = items?.filter((item) => item.requesterUserId === user?.id) ?? [];
  return <main><PageContainer><PageHeader eyebrow="Money" title="Request money" description="Requests expire server-side. Accepting a request uses Payflow's authoritative wallet transfer flow." actions={<Button variant="secondary" onClick={() => void load()}>Refresh</Button>} /><div aria-live="polite" className="mt-5">{message ? <p className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}</p> : null}{error ? <ErrorState message={error} /> : null}</div>
    <Card className="mt-7 p-6"><h2 className="text-lg font-bold">New request</h2><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={(event) => void create(event)}><SelectField id="request-payer" name="payerUserId" label="Request from" required><option value="">Choose contact</option>{contacts.map((item) => <option key={item.id} value={item.recipient.id}>{item.nickname || [item.recipient.firstName, item.recipient.lastName].filter(Boolean).join(' ')}</option>)}</SelectField><SelectField id="request-wallet" name="walletId" label="Receive into wallet" required><option value="">Choose wallet</option>{wallets.filter((item) => item.status === 'ACTIVE').map((item) => <option key={item.id} value={item.id}>{item.currency}</option>)}</SelectField><Field id="request-amount" name="amount" label="Amount" inputMode="decimal" pattern="\d+(\.\d{1,2})?" required /><Field id="request-expiry" name="expiresAt" label="Expires at" type="datetime-local" required /><Field id="request-note" name="note" label="Note (optional)" maxLength={240} className="sm:col-span-2" /><Button type="submit" disabled={saving}>{saving ? 'Sending…' : 'Send request'}</Button></form></Card>
    {items === null ? <LoadingState /> : <div className="mt-7 grid gap-6 lg:grid-cols-2"><RequestList title="Incoming" empty="No incoming requests" items={incoming} userId={user?.id} wallets={wallets} action={action} /><RequestList title="Outgoing and history" empty="No outgoing requests" items={outgoing} userId={user?.id} wallets={wallets} action={action} /></div>}
  </PageContainer></main>;
}
function RequestList({ title, empty, items, userId, wallets, action }: { title: string; empty: string; items: Request[]; userId?: string; wallets: Wallet[]; action: (item: Request, name: 'accept' | 'decline' | 'cancel', wallet?: string) => Promise<void> }) { const [selected, setSelected] = useState<Record<string, string>>({}); return <section><h2 className="text-lg font-bold">{title}</h2><div className="mt-4 space-y-3">{items.length === 0 ? <EmptyState title={empty} description="Request history will appear here." /> : items.map((item) => <Card key={item.id} className="p-5"><div className="flex justify-between gap-3"><p className="font-bold">{item.currency} {item.amount}</p><StatusBadge status={item.status} /></div><p className="mt-2 text-sm text-slate-600">{item.note || 'No note'} · expires {new Date(item.expiresAt).toLocaleString()}</p>{item.status === 'PENDING' && item.payerUserId === userId ? <div className="mt-4 flex flex-wrap gap-2"><select aria-label="Wallet used to accept" value={selected[item.id] ?? ''} onChange={(event) => setSelected((value) => ({ ...value, [item.id]: event.target.value }))} className="min-h-11 rounded-xl border px-3"><option value="">Choose {item.currency} wallet</option>{wallets.filter((wallet) => wallet.currency === item.currency && wallet.status === 'ACTIVE').map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.currency} wallet</option>)}</select><Button disabled={!selected[item.id]} onClick={() => void action(item, 'accept', selected[item.id])}>Accept</Button><Button variant="secondary" onClick={() => void action(item, 'decline')}>Decline</Button></div> : null}{item.status === 'PENDING' && item.requesterUserId === userId ? <Button variant="danger" className="mt-4" onClick={() => void action(item, 'cancel')}>Cancel</Button> : null}</Card>)}</div></section>; }
