'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Button, Card, EmptyState, ErrorState, Field, LoadingState, PageContainer, PageHeader, SelectField, StatusBadge } from '../components/customer';
import { getStoredUser, userAuthenticatedRequest } from '../lib/api';
import { addDecimalStrings, compareDecimalStrings, normalizeDecimal } from '../lib/money';
type Wallet = { id: string; currency: string; status: string }; type Contact = { id: string; nickname?: string | null; recipient: { id: string; firstName: string; lastName?: string | null } };
type Allocation = { id: string; participantUserId: string; amount: string; status: string }; type Split = { id: string; creatorUserId: string; walletId: string; currency: string; totalAmount: string; type: 'EQUAL' | 'EXACT'; status: string; note?: string | null; dueAt: string; allocations: Allocation[] };
const makeKey = (prefix: string) => `${prefix}:${crypto.randomUUID()}`;
function equalAmount(total: string, count: number): string | null { const normalized = normalizeDecimal(total); if (!normalized || count < 1) return null; const [whole, fraction] = normalized.split('.'); const hundred = BigInt(100); const units = BigInt(whole) * hundred + BigInt(fraction); if (units % BigInt(count) !== BigInt(0)) return null; const each = units / BigInt(count); return `${each / hundred}.${String(each % hundred).padStart(2, '0')}`; }
export default function SplitBillPage() {
  const [user] = useState(getStoredUser); const [items, setItems] = useState<Split[] | null>(null); const [contacts, setContacts] = useState<Contact[]>([]); const [wallets, setWallets] = useState<Wallet[]>([]); const [participants, setParticipants] = useState<string[]>([]); const [amounts, setAmounts] = useState<Record<string, string>>({}); const [type, setType] = useState<'EQUAL' | 'EXACT'>('EQUAL'); const [total, setTotal] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { if (!user) return; try { const [splits, people, walletValue] = await Promise.all([userAuthenticatedRequest<Split[]>('/customer-features/splits'), userAuthenticatedRequest<Contact[]>('/customer-features/contacts'), userAuthenticatedRequest<Wallet[] | { wallets?: Wallet[] }>(`/wallets/user/${user.id}`)]); setItems(splits); setContacts(people); setWallets(Array.isArray(walletValue) ? walletValue : walletValue.wallets ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load bill splits'); } }, [user]);
  useEffect(() => { void load(); }, [load]);
  function toggle(id: string) { setParticipants((value) => value.includes(id) ? value.filter((item) => item !== id) : [...value, id]); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setError(''); const wallet = wallets.find((item) => item.id === data.get('walletId')); const normalized = normalizeDecimal(total); if (!wallet || !normalized || compareDecimalStrings(normalized, '0.00') <= 0) { setError('Choose a wallet and enter a positive amount.'); return; } if (!participants.length) { setError('Select at least one participant.'); return; } const equal = equalAmount(normalized, participants.length); if (type === 'EQUAL' && !equal) { setError('For an equal split, the total must divide exactly to the smallest currency unit.'); return; } const allocations = participants.map((participantUserId) => ({ participantUserId, amount: type === 'EQUAL' ? equal as string : normalizeDecimal(amounts[participantUserId]) ?? '' })); const sum = allocations.reduce((value, item) => item.amount ? addDecimalStrings(value, item.amount) : value, '0.00'); if (allocations.some((item) => !item.amount) || compareDecimalStrings(sum, normalized) !== 0) { setError('Exact allocations must be positive and add up to the total.'); return; } try { await userAuthenticatedRequest('/customer-features/splits', { method: 'POST', body: JSON.stringify({ walletId: wallet.id, currency: wallet.currency, totalAmount: normalized, type, allocations, note: data.get('note') || undefined, dueAt: new Date(String(data.get('dueAt'))).toISOString(), idempotencyKey: makeKey('split') }) }); setMessage('Bill split created and participants notified.'); setParticipants([]); setAmounts({}); setTotal(''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create split'); } }
  async function act(path: string, body?: object) { setError(''); try { await userAuthenticatedRequest(`/customer-features${path}`, { method: 'POST', body: JSON.stringify(body ?? {}) }); setMessage('Split updated.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update split'); } }
  return <main><PageContainer><PageHeader eyebrow="Money" title="Split bill" description="Create exact decimal allocations and track authoritative wallet settlement status." actions={<Button variant="secondary" onClick={() => void load()}>Refresh</Button>} /><div aria-live="polite" className="mt-5">{message ? <p className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}</p> : null}{error ? <ErrorState message={error} /> : null}</div>
    <Card className="mt-7 p-6"><h2 className="text-lg font-bold">Create split</h2><form className="mt-5 space-y-5" onSubmit={(event) => void create(event)}><div className="grid gap-4 sm:grid-cols-2"><SelectField id="split-wallet" name="walletId" label="Receiving wallet" required><option value="">Choose wallet</option>{wallets.filter((item) => item.status === 'ACTIVE').map((item) => <option key={item.id} value={item.id}>{item.currency}</option>)}</SelectField><SelectField id="split-type" label="Allocation type" value={type} onChange={(event) => setType(event.target.value as 'EQUAL' | 'EXACT')}><option value="EQUAL">Equal</option><option value="EXACT">Exact</option></SelectField><Field id="split-total" label="Total amount" value={total} onChange={(event) => setTotal(event.target.value)} inputMode="decimal" required /><Field id="split-due" name="dueAt" label="Due at" type="datetime-local" required /><Field id="split-note" name="note" label="Note (optional)" maxLength={240} /></div><fieldset><legend className="text-sm font-semibold">Participants</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{contacts.map((contact) => { const id = contact.recipient.id; const checked = participants.includes(id); return <div key={contact.id} className="rounded-xl border p-3"><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={checked} onChange={() => toggle(id)} /><span className="font-medium">{contact.nickname || [contact.recipient.firstName, contact.recipient.lastName].filter(Boolean).join(' ')}</span></label>{checked && type === 'EXACT' ? <Field id={`allocation-${id}`} label="Amount" value={amounts[id] ?? ''} onChange={(event) => setAmounts((value) => ({ ...value, [id]: event.target.value }))} inputMode="decimal" required /> : checked && type === 'EQUAL' ? <p className="text-sm text-slate-600">{equalAmount(total, participants.length) ?? 'Enter a divisible total'}</p> : null}</div>; })}</div></fieldset><Button type="submit">Preview validation and create</Button></form></Card>
    <section className="mt-7"><h2 className="text-lg font-bold">Splits and history</h2>{items === null ? <LoadingState /> : items.length === 0 ? <EmptyState title="No splits" description="Created and participating splits will appear here." /> : <div className="mt-4 space-y-4">{items.map((item) => <SplitCard key={item.id} item={item} userId={user?.id} wallets={wallets} act={act} />)}</div>}</section>
  </PageContainer></main>;
}
function SplitCard({ item, userId, wallets, act }: { item: Split; userId?: string; wallets: Wallet[]; act: (path: string, body?: object) => Promise<void> }) { const mine = item.allocations.find((allocation) => allocation.participantUserId === userId); const [walletId, setWalletId] = useState(''); return <Card className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{item.currency} {item.totalAmount} · {item.type}</h3><p className="mt-1 text-sm text-slate-600">{item.note || 'No note'} · due {new Date(item.dueAt).toLocaleString()}</p></div><StatusBadge status={item.status} /></div><ul className="mt-4 space-y-2">{item.allocations.map((allocation) => <li key={allocation.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{allocation.participantUserId === userId ? 'Your share' : 'Participant'}</span><span className="font-semibold">{item.currency} {allocation.amount} · {allocation.status}</span></li>)}</ul>{mine?.status === 'PENDING' && ['OPEN', 'PARTIALLY_PAID'].includes(item.status) ? <div className="mt-4 flex flex-wrap gap-2"><select aria-label="Wallet for split payment" value={walletId} onChange={(event) => setWalletId(event.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">Choose {item.currency} wallet</option>{wallets.filter((wallet) => wallet.currency === item.currency && wallet.status === 'ACTIVE').map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.currency} wallet</option>)}</select><Button disabled={!walletId} onClick={() => void act(`/split-allocations/${mine.id}/pay`, { sourceWalletId: walletId, idempotencyKey: makeKey('split-pay') })}>Pay share</Button></div> : null}{item.creatorUserId === userId && ['OPEN', 'PARTIALLY_PAID'].includes(item.status) ? <Button className="mt-4" variant="danger" onClick={() => void act(`/splits/${item.id}/cancel`)}>Cancel split</Button> : null}</Card>; }
